/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.falhad.nextpay

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test
    fun testRequestToken() {
//        val nextPay = NextPay("")
//        val tokenResponse = nextPay.requestToken("testOrderId", 1000, "http://localhost:8080/payment")
//        println(tokenResponse.transId)
//        println(tokenResponse.paymentURL())
    }
}
